# Generated by Django 5.0.14 on 2025-07-30 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaGuarderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_laborales', models.CharField(max_length=255)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('nombre_guarderia', models.CharField(max_length=255)),
                ('direccion_guarderia', models.TextField()),
                ('nombre_menor', models.CharField(max_length=255)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('puede_solicitar_guarderia', 'Puede solicitar constancia de guardería')],
            },
        ),
    ]
