# Generated by Django 5.0.14 on 2025-08-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_requests', '0002_constanciaguarderia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constanciaguarderia',
            options={'permissions': [('puede_solicitar_guarderia', 'Puede solicitar constancia de guardería'), ('puede_solicitar_personal', 'Puede solicitar personal')]},
        ),
    ]
