# Generated by Django 5.0.14 on 2025-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_requests', '0003_alter_constanciaguarderia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='constanciaguarderia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
