# Generated by Django 5.0.14 on 2025-08-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_requests', '0004_constanciaguarderia_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constanciaguarderia',
            name='estado',
        ),
    ]
