# Generated by Django 5.0.14 on 2025-08-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_requests', '0006_constanciaguarderia_nacimiento_menor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constanciaguarderia',
            name='nacimiento_menor',
            field=models.DateField(verbose_name='Fecha de nacimiento del menor'),
        ),
    ]
