# Generated by Django 5.0.14 on 2025-08-11 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_requests', '0007_alter_constanciaguarderia_nacimiento_menor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constanciaguarderia',
            options={'permissions': [('puede_solicitar_guarderia', 'Puede solicitar constancia de guardería'), ('puede_solicitar_personal', 'Puede solicitar personal'), ('puede_responder_guarderia', 'Puede responder solicitudes de guardería')]},
        ),
        migrations.AddField(
            model_name='constanciaguarderia',
            name='pdf_respuesta',
            field=models.FileField(blank=True, null=True, upload_to='guarderia_respuestas/'),
        ),
        migrations.AddField(
            model_name='constanciaguarderia',
            name='respondido_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constanciaguarderia',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarderia_respuestas_hechas', to=settings.AUTH_USER_MODEL),
        ),
    ]
