# Generated by Django 5.0.14 on 2025-08-12 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_requests', '0008_alter_constanciaguarderia_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constanciaguarderia',
            options={'permissions': [('puede_solicitar_guarderia', 'Puede solicitar constancia de guardería'), ('puede_solicitar_personal', 'Puede solicitar personal')]},
        ),
        migrations.AddConstraint(
            model_name='constanciaguarderia',
            constraint=models.UniqueConstraint(condition=models.Q(('pdf_respuesta__isnull', True)), fields=('empleado',), name='uniq_guarderia_pendiente_por_empleado'),
        ),
    ]
