# Generated by Django 5.0.14 on 2025-12-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_requests', '0009_alter_constanciaguarderia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constanciaguarderia',
            options={'permissions': [('Modulo_constancias', 'Acceso al Módulo de Constancias'), ('puede_solicitar_guarderia', 'Puede solicitar constancia de guardería'), ('puede_solicitar_personal', 'Puede solicitar personal')]},
        ),
    ]
