# Generated by Django 5.0.14 on 2026-01-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_requests', '0010_alter_constanciaguarderia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='constanciaguarderia',
            name='periodo_vacacional',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Periodo Vacacional'),
        ),
        migrations.AddField(
            model_name='constanciaguarderia',
            name='registro_patronal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro Patronal'),
        ),
    ]
