# Generated by Django 5.0.11 on 2025-03-24 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del empleado', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_level',
            field=models.CharField(blank=True, help_text='Nivel educativo alcanzado por el empleado (ej. Preparatoria, Licenciatura, etc.)', max_length=100, null=True, verbose_name='Nivel de estudios'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo de contacto del empleado', max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el empleado está actualmente activo en la empresa', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas o comentarios generales sobre el empleado', null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto del empleado para su perfil', null=True, upload_to='employees/photos/', verbose_name='Fotografía'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Fecha en que el empleado dejó de laborar', null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Cuenta de usuario vinculada al empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
