# Generated by Django 5.0.14 on 2026-05-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncentivosConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('Modulo_incentivos', 'Puede acceder al módulo de incentivos')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
