# Generated by Django 5.0.14 on 2026-05-27 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_add_leader_to_employee'),
        ('incentives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentivoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, help_text='Nulo si es solo palomita (ej. Diesel)', max_digits=10, null=True, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentivo_registros', to='employee.employee', verbose_name='Empleado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentivos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de incentivo',
                'verbose_name_plural': 'Registros de incentivos',
                'unique_together': {('employee', 'tipo', 'fecha')},
            },
        ),
    ]
