# Generated by Django 5.0.14 on 2026-05-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0002_incentivoregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivoregistro',
            name='comentario',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Comentario'),
        ),
    ]
