# Generated by Django 5.0.14 on 2026-05-29 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_add_leader_to_employee'),
        ('incentives', '0003_add_comentario_to_incentivoregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentivoregistro',
            name='comentario',
        ),
        migrations.CreateModel(
            name='ComentarioSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('week_start', models.DateField()),
                ('comentario', models.CharField(blank=True, default='', max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_semana', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Comentario de semana',
                'verbose_name_plural': 'Comentarios de semana',
                'unique_together': {('employee', 'tipo', 'week_start')},
            },
        ),
    ]
