# Generated by Django 5.0.14 on 2026-06-03 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0004_comentario_semana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaCerrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True, verbose_name='Inicio de semana')),
                ('cerrada_at', models.DateTimeField(auto_now_add=True)),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semanas_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por')),
            ],
            options={
                'verbose_name': 'Semana cerrada',
                'verbose_name_plural': 'Semanas cerradas',
            },
        ),
    ]
