# Generated by Django 5.0.14 on 2026-06-25 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0005_semana_cerrada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_key', models.CharField(max_length=50, verbose_name='Clave de estación')),
                ('mes', models.DateField(verbose_name='Mes (primer día)')),
                ('maxima', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Máxima')),
                ('gasolina_super', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Super')),
                ('diesel', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Diesel')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_venta', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Presupuesto de venta',
                'verbose_name_plural': 'Presupuestos de venta',
                'unique_together': {('team_key', 'mes')},
            },
        ),
    ]
