# Generated by Django 5.0.14 on 2026-07-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0006_add_presupuesto_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaltaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, verbose_name='Número de empleado')),
                ('semana', models.DateField(verbose_name='Semana (lunes)')),
                ('faltas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Faltas')),
                ('equipo', models.CharField(blank=True, max_length=100, verbose_name='Equipo')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Falta de empleado',
                'verbose_name_plural': 'Faltas de empleados',
                'unique_together': {('employee_number', 'semana')},
            },
        ),
    ]
