# Generated by Django 5.0.14 on 2026-07-29 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0008_presupuestoventa_semanal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incentivosconfig',
            options={'default_permissions': (), 'managed': False, 'permissions': [('Modulo_incentivos', 'Puede acceder al módulo de incentivos'), ('configurar_incentivos', 'Puede configurar montos de incentivos')]},
        ),
        migrations.CreateModel(
            name='ConfiguracionIncentivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado_primer_dia', models.IntegerField(default=200, help_text='Monto del primer día de Encargado por semana.', verbose_name='Encargado — primer día ($)')),
                ('encargado_incremento', models.IntegerField(default=100, help_text='Monto que se agrega por cada día adicional de Encargado.', verbose_name='Encargado — incremento por día adicional ($)')),
                ('encargado_max_dias', models.IntegerField(default=6, verbose_name='Encargado — máximo de días por semana')),
                ('diesel_por_dia', models.IntegerField(default=50, verbose_name='Diesel — monto por día ($)')),
                ('diesel_max_dias', models.IntegerField(default=6, verbose_name='Diesel — máximo de días por semana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_incentivos', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración de incentivos',
                'verbose_name_plural': 'Configuración de incentivos',
            },
        ),
    ]
