# Generated by Django 5.0.14 on 2026-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0009_configuracion_incentivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionincentivos',
            name='venta_monto_antiguedad',
            field=models.IntegerField(default=230, help_text='Monto del bono de Venta para empleados con antigüedad hasta 2019.', verbose_name='Venta — monto antigüedad ≤ 2019 ($)'),
        ),
        migrations.AddField(
            model_name='configuracionincentivos',
            name='venta_monto_bajio',
            field=models.IntegerField(default=240, help_text='Monto del bono de Venta para estaciones Bajío.', verbose_name='Venta — monto Bajío ($)'),
        ),
        migrations.AddField(
            model_name='configuracionincentivos',
            name='venta_monto_regular',
            field=models.IntegerField(default=200, help_text='Monto del bono de Venta para el resto de empleados.', verbose_name='Venta — monto regular ($)'),
        ),
    ]
