# Generated by Django 5.0.14 on 2026-07-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0010_configuracion_incentivos_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionincentivos',
            name='mistery_monto',
            field=models.IntegerField(default=50, help_text='Monto para todos los empleados de la estación que ganó Mistery.', verbose_name='Mistery — monto general ($)'),
        ),
        migrations.AddField(
            model_name='configuracionincentivos',
            name='mistery_monto_evaluado',
            field=models.IntegerField(default=500, help_text='Monto para la persona que fue evaluada en el Mistery.', verbose_name='Mistery — monto persona evaluada ($)'),
        ),
    ]
