# Generated by Django 5.0.14 on 2026-08-27 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0011_mistery_montos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaECV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría ECV',
                'verbose_name_plural': 'Categorías ECV',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorECV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('venta_gas', 'Venta Gasolina'), ('venta_diesel', 'Venta Diésel'), ('mistery', 'Mistery Shopper'), ('faltante', 'Faltante'), ('incidencia', 'Incidencia en cortes')], max_length=20, verbose_name='Indicador')),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ponderación (%)')),
                ('umbral_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umbral mínimo (80%)')),
                ('umbral_objetivo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umbral objetivo (100%)')),
                ('umbral_excelente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umbral excelente (120%)')),
                ('unidad', models.CharField(choices=[('porcentaje', 'Porcentaje (%)'), ('monto', 'Monto ($)'), ('conteo', 'Conteo')], max_length=15, verbose_name='Unidad')),
                ('direccion', models.CharField(choices=[('mayor', 'Mayor es mejor'), ('menor', 'Menor es mejor')], default='mayor', help_text='Si el valor más alto o más bajo es mejor.', max_length=10, verbose_name='Dirección')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='incentives.categoriaecv', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Indicador ECV',
                'verbose_name_plural': 'Indicadores ECV',
                'ordering': ['orden'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
    ]
