# Generated by Django 5.0.14 on 2026-09-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0014_prenomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenominaregistro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prenominaupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
