# Generated by Django 5.0.14 on 2025-11-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
