# Generated by Django 5.0.14 on 2025-11-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_emailed_at_alter_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='email_channels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
