# Generated by Django 5.0.14 on 2025-12-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_email_channels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('Modulo_noticias', 'Acceso al Módulo de Noticias')]},
        ),
    ]
