# Generated by Django 5.0.14 on 2026-02-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='¿Es Prioritario?'),
        ),
    ]
