# Generated by Django 5.0.14 on 2025-09-02 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Puntos')),
                ('color_hex', models.CharField(default='#1E3361', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color válido en formato #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='recognitions/covers/', verbose_name='Imagen de portada')),
                ('confetti_enabled', models.BooleanField(default=True, verbose_name='Efecto confeti')),
                ('show_points', models.BooleanField(default=False, verbose_name='Mostrar puntaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
