# Generated by Django 5.0.14 on 2025-09-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitions', '0003_recognitioncomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='recognitions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('recognition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recognitions.recognition')),
            ],
        ),
    ]
