# Generated by Django 5.0.14 on 2025-11-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitions', '0005_recognitionlike_recognition_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recognition',
            options={'ordering': ('-published_at', '-created_at')},
        ),
        migrations.AddField(
            model_name='recognition',
            name='email_channels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recognition',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recognition',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recognition',
            name='notify_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recognition',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo debe publicarse (hora local).', null=True),
        ),
        migrations.AddField(
            model_name='recognition',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='recognition',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('published', 'Publicado')], db_index=True, default='draft', max_length=20),
        ),
    ]
