# Generated by Django 5.0.14 on 2025-12-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognitions', '0006_alter_recognition_options_recognition_email_channels_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recognition',
            options={'ordering': ('-published_at', '-created_at'), 'permissions': [('Modulo_comunicados', 'Acceso al Módulo de Comunicados')]},
        ),
    ]
