# Generated by Django 5.0.14 on 2026-01-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitions', '0007_alter_recognition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
