# Generated by Django 5.0.14 on 2026-02-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('recognitions', '0008_recognition_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recognition',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='visible_recognitions', to='auth.group'),
        ),
    ]
