# Generated by Django 5.0.14 on 2026-02-09 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitions', '0009_recognition_is_public_recognition_target_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recognition',
            name='priority_viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_priority_recognitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
