# Generated by Django 5.0.14 on 2026-04-10 16:25

import apps.recognitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitions', '0011_recognitionlike_reaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.recognitions.models.recognition_image_upload),
        ),
        migrations.AlterField(
            model_name='recognitioncategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.recognitions.models.recognition_cover_upload, verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='recognitionmedia',
            name='file',
            field=models.ImageField(upload_to=apps.recognitions.models.recognition_media_upload),
        ),
    ]
