# Generated by Django 5.0.14 on 2026-06-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognitions', '0012_alter_recognition_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2000)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('recognition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='recognitions.recognition')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
