# Generated by Django 5.0.14 on 2025-12-09 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, max_length=20, verbose_name='# Empleado')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Completo')),
                ('job_position', models.CharField(blank=True, max_length=150, verbose_name='Puesto')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Patrón / Empresa')),
                ('saving_fund_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ahorro Total (al solicitar)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Préstamo Solicitado')),
                ('weeks', models.PositiveIntegerField(verbose_name='Plazos (Semanas)')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Pago Semanal')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('paid', 'Pagado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del préstamo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Préstamo',
                'verbose_name_plural': 'Solicitudes de Préstamo',
                'ordering': ['-created_at'],
            },
        ),
    ]
