# Generated by Django 5.0.14 on 2025-12-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanrequest',
            options={'ordering': ['-created_at'], 'permissions': [('Modulo_herramientas', 'Acceso al Módulo de Herramientas')], 'verbose_name': 'Solicitud de Préstamo', 'verbose_name_plural': 'Solicitudes de Préstamo'},
        ),
    ]
