# Generated by Django 5.0.14 on 2026-07-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_loanrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='unlocked',
            field=models.BooleanField(default=False, verbose_name='Desbloqueado por superusuario'),
        ),
    ]
