# Generated by Django 5.0.14 on 2026-07-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_add_unlocked_to_loanrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanrequest',
            options={'ordering': ['-created_at'], 'permissions': [('Modulo_herramientas', 'Acceso al Módulo de Herramientas'), ('desbloquear_prestamos', 'Puede desbloquear préstamos')], 'verbose_name': 'Solicitud de Préstamo', 'verbose_name_plural': 'Solicitudes de Préstamo'},
        ),
    ]
