# Generated by Django 5.0.11 on 2025-02-19 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la lección.', max_length=140, verbose_name='Título')),
                ('lesson_type', models.CharField(choices=[('Video', 'Video'), ('Lectura', 'Lectura'), ('Articulo', 'Artículo'), ('SCORM', 'SCORM')], help_text='Tipo de lección.', max_length=20, verbose_name='Tipo de lección')),
                ('description', models.TextField(help_text='Descripción de la lección.', verbose_name='Descripción')),
                ('resource', models.FileField(blank=True, help_text='Archivo adjunto o enlace a un recurso externo.', null=True, upload_to='lessons/resources/', verbose_name='Recurso')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('Texto', 'Texto'), ('Respuesta Unica', 'Respuesta Única'), ('Respuesta Multiple', 'Respuesta Múltiple')], help_text='Tipo de pregunta.', max_length=20, verbose_name='Tipo de pregunta')),
                ('question_text', models.CharField(help_text='Texto de la pregunta.', max_length=200, verbose_name='Pregunta')),
                ('single_answer', models.TextField(blank=True, help_text="Respuesta única en caso de ser de tipo 'Texto'.", null=True, verbose_name='Respuesta única')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la categoría del curso.', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción de la categoría del curso.', verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización.', null=True, verbose_name='Actualizado en')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='Creado en')),
                ('user', models.ForeignKey(help_text='Usuario que creó la categoría.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Categoría de curso',
                'verbose_name_plural': 'Categorías de cursos',
            },
        ),
        migrations.CreateModel(
            name='CourseHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del curso.', max_length=140, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción del curso.', verbose_name='Descripción')),
                ('duration', models.FloatField(help_text='Duración del curso en horas.', verbose_name='Duración')),
                ('portrait', models.ImageField(help_text='Imagen del curso (JPG, PNG, GIF, 800x400px).', upload_to='courses/', verbose_name='Imagen del curso')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='Categoría del curso.', on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory', verbose_name='Categoría')),
                ('user', models.ForeignKey(help_text='Usuario que creó el curso.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_link', models.URLField(help_text='Enlace al archivo adjunto.', verbose_name='Enlace del archivo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(help_text='Lección a la que pertenece el archivo adjunto.', on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Lección')),
            ],
            options={
                'verbose_name': 'Archivo adjunto',
                'verbose_name_plural': 'Archivos adjuntos',
            },
        ),
        migrations.CreateModel(
            name='ModuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del módulo.', max_length=140, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción del módulo.', verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_header', models.ForeignKey(help_text='Curso al que pertenece el módulo.', on_delete=django.db.models.deletion.CASCADE, to='courses.courseheader', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module_content',
            field=models.ForeignKey(help_text='Módulo al que pertenece la lección.', on_delete=django.db.models.deletion.CASCADE, to='courses.modulecontent', verbose_name='Módulo'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(help_text='Texto de la respuesta.', max_length=200, verbose_name='Respuesta')),
                ('is_correct', models.BooleanField(default=False, help_text='Indica si la respuesta es correcta.', verbose_name='Es correcta')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(help_text='Pregunta a la que pertenece la respuesta.', on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del cuestionario.', max_length=140, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción del cuestionario.', verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_header', models.ForeignKey(help_text='Curso al que pertenece el cuestionario.', on_delete=django.db.models.deletion.CASCADE, to='courses.courseheader', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(help_text='Cuestionario al que pertenece la pregunta.', on_delete=django.db.models.deletion.CASCADE, to='courses.quiz', verbose_name='Cuestionario'),
        ),
    ]
