# Generated by Django 5.0.11 on 2025-02-19 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la que el usuario fue asignado al curso.', verbose_name='Fecha de asignación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('failed', 'No aprobado')], default='pending', help_text='Estado actual del curso para este usuario.', max_length=20, verbose_name='Estado')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de progreso del usuario en el curso (0-100).', max_digits=5, verbose_name='Progreso')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha en la que el usuario completó el curso (si aplica).', null=True, verbose_name='Fecha de finalización')),
                ('last_accessed', models.DateTimeField(blank=True, help_text='Última fecha en la que el usuario accedió al curso.', null=True, verbose_name='Último acceso')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la inscripción del usuario en este curso.', verbose_name='Notas')),
                ('course', models.ForeignKey(help_text='Curso al que está inscrito el usuario.', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='courses.courseheader', verbose_name='Curso')),
                ('user', models.ForeignKey(help_text='Usuario al que se le ha asignado el curso.', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Curso Inscrito',
                'verbose_name_plural': 'Cursos Inscritos',
                'db_table': 'enrolled_course',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
