# Generated by Django 5.0.11 on 2025-03-10 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseassignment_courseconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconfig',
            name='audience',
            field=models.CharField(choices=[('all_users', 'Todos los usuarios'), ('segment', 'Requiere segmentación')], default='all_users', max_length=15, verbose_name='Audiencia'),
        ),
        migrations.AlterField(
            model_name='courseconfig',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='courses.courseheader', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='courseconfig',
            name='course_type',
            field=models.CharField(choices=[('mandatory', 'Obligatorio'), ('optional', 'Opcional')], default='mandatory', max_length=10, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='courseconfig',
            name='deadline',
            field=models.IntegerField(default=90, verbose_name='Plazo límite en días'),
        ),
        migrations.AlterField(
            model_name='courseheader',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory', verbose_name='Categoría del curso:'),
        ),
        migrations.AlterField(
            model_name='courseheader',
            name='description',
            field=models.TextField(verbose_name='Descripción del curso:'),
        ),
        migrations.AlterField(
            model_name='courseheader',
            name='duration',
            field=models.FloatField(verbose_name='Duración del curso en horas:'),
        ),
        migrations.AlterField(
            model_name='courseheader',
            name='portrait',
            field=models.ImageField(upload_to='courses/', verbose_name='Imagen del curso (JPG, PNG, GIF, 800x400px).'),
        ),
        migrations.AlterField(
            model_name='courseheader',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Título del curso:'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='resource',
            field=models.FileField(blank=True, help_text='Archivo adjunto o enlace a un recurso externo.', null=True, upload_to='lessons/', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseheader', verbose_name='Curso al que pertenece el cuestionario.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(verbose_name='Descripción del cuestionario.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Título del cuestionario.'),
        ),
    ]
