# Generated by Django 5.0.11 on 2025-04-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseconfig_audience_and_more'),
        ('employee', '0002_employee_birth_date_employee_education_level_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Ubicaciones físicas a las que se asigna el curso.', to='location.location', verbose_name='Ubicaciones'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='positions',
            field=models.ManyToManyField(blank=True, help_text='Posiciones laborales a las que se asigna el curso.', to='employee.jobposition', verbose_name='Posiciones'),
        ),
    ]
