# Generated by Django 5.0.14 on 2025-06-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_question_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.AddField(
            model_name='answer',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explicación de la respuesta (opcional).', null=True, verbose_name='Explicación'),
        ),
    ]
