# Generated by Django 5.0.14 on 2025-06-10 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_answer_explanation_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.PositiveIntegerField(default=1, help_text='Puntaje que vale esta pregunta'),
        ),
        migrations.CreateModel(
            name='QuizConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score', models.PositiveIntegerField(default=60, help_text='Porcentaje mínimo para aprobar (0-100)')),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Número máximo de intentos (en blanco = sin límite)', null=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Límite de tiempo en minutos (opcional)', null=True)),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Mostrar respuestas correctas al finalizar')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='courses.quiz', verbose_name='Cuestionario')),
            ],
            options={
                'verbose_name': 'Configuración del Cuestionario',
                'verbose_name_plural': 'Configuraciones de Cuestionarios',
            },
        ),
    ]
