# Generated by Django 5.0.14 on 2025-07-16 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursecertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subcategoría')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.coursecategory')),
            ],
            options={
                'verbose_name': 'Subcategoría del Curso',
                'verbose_name_plural': 'Subcategorías del Curso',
            },
        ),
        migrations.AddField(
            model_name='courseheader',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursesubcategory', verbose_name='Subcategoría del curso'),
        ),
    ]
