# Generated by Django 5.0.14 on 2025-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_coursesubcategory_courseheader_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseheader',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='coursesubcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='courseheader',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, to='courses.coursesubcategory', verbose_name='Subcategorías'),
        ),
    ]
