# Generated by Django 5.0.14 on 2025-07-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_courseheader_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseheader',
            name='sub_categories',
        ),
        migrations.CreateModel(
            name='CourseSubCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseheader', verbose_name='Curso')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesubcategory', verbose_name='Subcategoría')),
            ],
            options={
                'verbose_name': 'Relación Curso - Subcategoría',
                'verbose_name_plural': 'Relaciones Curso - Subcategoría',
                'unique_together': {('course', 'subcategory')},
            },
        ),
    ]
