# Generated by Django 5.0.14 on 2025-07-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_courseheader_sub_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseconfig',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='El curso se archivará al concluir el plazo o agotarse los intentos.', verbose_name='¿Archivar automáticamente al finalizar?'),
        ),
    ]
