# Generated by Django 5.0.14 on 2025-07-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_courseconfig_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseheader',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
