# Generated by Django 5.0.14 on 2025-08-21 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_courseheader_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='courses.courseheader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'course'], name='courses_cou_user_id_e42ca4_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
