# Generated by Django 5.0.14 on 2025-12-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_courseseen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseheader',
            options={'permissions': [('Modulo_cursos', 'Acceso al Módulo de Cursos')], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
