# Generated by Django 5.0.14 on 2026-01-21 00:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0008_employee_daily_salary_employee_indemnification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Ciclo')),
                ('year', models.IntegerField(verbose_name='Año Fiscal')),
                ('review_type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('is_360', models.BooleanField(default=False, verbose_name='Es 360°')),
                ('status', models.CharField(choices=[('setup', 'Configuración'), ('active', 'Activa / En Curso'), ('closed', 'Cerrada / Finalizada')], default='setup', max_length=20, verbose_name='Estado')),
                ('scope_type', models.CharField(choices=[('excel', 'Carga Excel'), ('all', 'Toda la Organización'), ('manual', 'Selección Manual')], default='excel', max_length=20, verbose_name='Tipo de Selección')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('target_employees', models.ManyToManyField(blank=True, related_name='review_cycles_targeted', to='employee.employee', verbose_name='Empleados Objetivo')),
            ],
            options={
                'verbose_name': 'Ciclo de Evaluación',
                'verbose_name_plural': 'Ciclos de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_self', 'Pendiente Autoevaluación'), ('pending_manager', 'Pendiente Evaluación Jefe'), ('completed', 'Completada')], default='draft', max_length=20)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Pobre (Poor)'), (2, 'Regular (Fair)'), (3, 'Bueno (Good)'), (4, 'Muy Bueno (Very Good)'), (5, 'Excelente (Excellent)')], null=True, verbose_name='Calificación Final')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios Generales')),
                ('date_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_performance_reviews', to='employee.employee', verbose_name='Empleado Evaluado')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to='employee.employee', verbose_name='Evaluador Principal')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.performancereviewcycle', verbose_name='Ciclo')),
            ],
            options={
                'verbose_name': 'Evaluación de Desempeño',
                'verbose_name_plural': 'Evaluaciones de Desempeño',
                'unique_together': {('cycle', 'employee')},
            },
        ),
    ]
