# Generated by Django 5.0.14 on 2026-02-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_employee_unique_employee_identity_and_more'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together={('cycle', 'employee', 'reviewer')},
        ),
    ]
