# Generated by Django 5.0.14 on 2026-03-04 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_alter_performancereview_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_key', models.CharField(max_length=50, verbose_name='Clave Competencia')),
                ('logro', models.IntegerField(blank=True, null=True, verbose_name='Puntuación (1-3)')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios Líder')),
                ('compromisos', models.TextField(blank=True, null=True, verbose_name='Compromisos Empleado')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='performance.performancereview', verbose_name='Evaluación')),
            ],
            options={
                'unique_together': {('review', 'competencia_key')},
            },
        ),
    ]
