# Generated by Django 5.0.14 on 2026-03-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_performancereviewanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_self', 'Pendiente Autoevaluación'), ('pending_manager', 'Pendiente Evaluación Jefe'), ('completed', 'Completada'), ('closed', 'Cerrada por Sistema')], default='draft', max_length=20),
        ),
    ]
