"""
Django settings for hrms project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

MEDIA_URL = '/media/'  # URL base para acceder a archivos subidos
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Carpet a donde se guardarán los archivos

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)xa@r^^@7z#&_6qrg*5e8e_@yq4pixyw3ow4vhvl-ylrb4h-*7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "authapp",
    "departments",
    "apps.users",
    "apps.news",
    "apps.recognitions",
    "apps.forms_requests.apps.FormsRequestsConfig",
    "apps.vacations",
    "apps.performance",
    "apps.objectives",
    "apps.org_chart",
    "apps.archive",
    "apps.onboarding",
    "apps.surveys",
    "apps.documents",
    "apps.job_offers",
    "apps.policies",
    "apps.career_plan",
    'formtools',
    'apps.employee.apps.EmployeeConfig',
    'apps.location',
    'apps.endpoints',
    'apps.staff_requisitions',
    'apps.notifications',
    "apps.courses.apps.CoursesConfig",
    "apps.monitoring.apps.MonitoringConfig",
    'apps.tools',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',   # ← ARRIBA
    'apps.monitoring.middleware.IdleTimeoutMiddleware',          # ← tus middlewares
    'apps.monitoring.middleware.DailyUsageMiddleware',           # ← van DESPUÉS de Auth
    'apps.users.middleware.ForcePasswordChangeMiddleware',       # ← si lo usas, aquí está bien
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 30 min por inactividad (para server y para la vista)
SESSION_COOKIE_AGE = 30 * 60
SESSION_SAVE_EVERY_REQUEST = True
IDLE_TIMEOUT_SECONDS = 30 * 60

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "daily-usage-cache",
    }
}

ROOT_URLCONF = 'hrms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Aquí agregas la ruta a tu directorio 'templates'
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hrms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv("DB_ENGINE", "mssql"),
        'NAME': os.getenv("DB_NAME", "hrms"),
        'USER': os.getenv("DB_USER", "cguser"),
        'PASSWORD': os.getenv("DB_PASSWORD", ""),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "1433"),
        'OPTIONS': {
            'driver': os.getenv("DB_DRIVER", "ODBC Driver 17 for SQL Server"),
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'apps.users.validators.CustomComplexityValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = "America/Ciudad_Juarez"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# URL pública de los archivos estáticos
STATIC_URL = '/static/'

# Ruta donde Django pondrá los archivos al ejecutar collectstatic (solo para producción)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')

# Directorios donde buscar archivos estáticos en desarrollo (CSS/JS de tus apps, etc.)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/home/" 
LOGOUT_REDIRECT_URL = "/"  

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").strip().lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# settings.py
TEST_NEWS_EMAIL = os.getenv("TEST_NEWS_EMAIL", "").strip()

SITE_BASE_URL = os.getenv("SITE_BASE_URL", "")