STATION_TEAMS = {
    '4188': 'Gemela Grande',
    '11007': 'Aguascalientes',
    '1149': 'Lerdo',
    '2526': 'Lopez Mateos',
    '4179': 'Gemela Chica',
    '5317': 'Municipio Libre',
    '5465': 'Aztecas',
    '6410': 'Misiones',
    '6947': 'Puerto de Palos',
    '7167': 'Miguel de la Madrid',
    '8244': 'Permuta',
    '9191': 'Electrolux',
    '9235': 'Aeronáutica',
    '9885': 'Custodia',
    '9893': 'Anapra',
    '2172': 'Parral',
    '1376': 'Delicias',
    '5170': 'Plutarco',
    '1163': 'Tecnológico',
    '23214': 'Hermanos Escobar',
    '12900': 'El Castaño',
    'Ejercito': 'Ejército Nacional',
    'Satelite': 'Satélite',
    'Fuentes': 'Las Fuentes',
    'Clara': 'Clara',
    'Solis': 'Solis',
    'Santiago': 'Santiago Troncoso',
    'Jarudo': 'Jarudo',
    'Villahumada': 'Villa Ahumada',
    'Travel Center': 'Travel Center',
    'Picachos': 'Picachos',
    'Ventanas': 'Ventanas',
    'San Rafael': 'San Rafael',
    'Puertecito': 'Puertecito',
    'Jesus Maria': 'Jesús María',
    'Gabriela Mistral': 'Gabriela Mistral',
    'Praxedis': 'PRAXEDIS',
    'Colosio': 'Colosio',
}
