STATION_TEAMS = {
    '4188': 'Gemela Grande',
    '11007': 'Aguascalientes',
    '1149': 'Lerdo',
    '2526': 'Lopez Mateos',
    '4179': 'Gemela Chica',
    '5317': 'Municipio Libre',
    '5465': 'Aztecas',
    '6410': 'Misiones',
    '6947': 'Puerto de Palos',
    '7167': 'Miguel de la Madrid',
    '8244': 'Permuta',
    '9191': 'Electrolux',
    '9235': 'Aeronáutica',
    '9885': 'Custodia',
    '9893': 'Anapra',
    '2172': 'Parral',
    '1376': 'Delicias',
    '5170': 'Plutarco',
    '1163': 'Tecnológico',
    '23214': 'Hermanos Escobar',
    '12900': 'El Castaño',
    'Ejercito': 'Ejército Nacional',
    'Satelite': 'Satélite',
    'Fuentes': 'Las Fuentes',
    'Clara': 'Clara',
    'Solis': 'Solis',
    'Santiago': 'Santiago Troncoso',
    'Jarudo': 'Jarudo',
    'Villahumada': 'Villa Ahumada',
    'Travel Center': 'Travel Center',
    'Picachos': 'Picachos',
    'Ventanas': 'Ventanas',
    'San Rafael': 'San Rafael',
    'Puertecito': 'Puertecito',
    'Jesus Maria': 'Jesús María',
    'Gabriela Mistral': 'Gabriela Mistral',
    'Praxedis': 'PRAXEDIS',
    'Colosio': 'Colosio',
}

# Mapeo de códigos numéricos del Excel → key en STATION_TEAMS
# Para las estaciones cuyo Employee.team usa clave de texto, no número.
EXCEL_CODE_TO_TEAM_KEY = {
    '9733':  'Ejercito',
    '4457':  'Satelite',
    '1159':  'Fuentes',
    '1156':  'Clara',
    '10141': 'Solis',
    '12097': 'Santiago',
    '1148':  'Jarudo',
    '1242':  'Villahumada',
    '24938': 'Travel Center',
    '24499': 'Picachos',
    '24500': 'Ventanas',
    '14946': 'San Rafael',
    '15071': 'Puertecito',
    '15901': 'Jesus Maria',
    '12442': 'Gabriela Mistral',
    '3184':  'Praxedis',
    '22600': 'Colosio',
}
