from django.urls import path
from .views import (
    incentives_dashboard,
    incentives_dashboard_admin,
    incentives_dashboard_zona,
    incentives_dashboard_user,
    incentives_dashboard_manager,
    incentives_dashboard_operaciones,
    parsear_excel_ventas,
    guardar_presupuesto_ventas,
    presupuesto_mes_json,
    toggle_incentivo,
    toggle_semana_cerrada,
    semana_data,
    guardar_comentario,
    resumen_global,
    ventas_sg12_json,
    sync_venta_semana,
    sync_mistery_semana,
    mistery_evaluado_json,
    marcar_evaluado_mistery,
    presupuesto_semana_json,
    guardar_presupuesto_semana,
    configuracion_incentivos,
    desglose_bonos,
    parsear_prenomina,
    guardar_prenomina,
)

urlpatterns = [
    path('', incentives_dashboard, name='incentives_dashboard'),
    path('admin/', incentives_dashboard_admin, name='incentives_dashboard_admin'),
    path('zona/', incentives_dashboard_zona, name='incentives_dashboard_zona'),
    path('manager/', incentives_dashboard_manager, name='incentives_dashboard_manager'),
    path('operaciones/', incentives_dashboard_operaciones, name='incentives_dashboard_operaciones'),
    path('user/', incentives_dashboard_user, name='incentives_dashboard_user'),
    path('toggle/', toggle_incentivo, name='toggle_incentivo'),
    path('cerrar-semana/', toggle_semana_cerrada, name='toggle_semana_cerrada'),
    path('semana/', semana_data, name='semana_data'),
    path('comentario/', guardar_comentario, name='guardar_comentario'),
    path('resumen-global/', resumen_global, name='resumen_global'),
    path('parsear-excel-ventas/', parsear_excel_ventas, name='parsear_excel_ventas'),
    path('guardar-presupuesto-ventas/', guardar_presupuesto_ventas, name='guardar_presupuesto_ventas'),
    path('ventas-sg12/', ventas_sg12_json, name='ventas_sg12_json'),
    path('sync-venta/', sync_venta_semana, name='sync_venta_semana'),
    path('sync-mistery/', sync_mistery_semana, name='sync_mistery_semana'),
    path('mistery-evaluado/', mistery_evaluado_json, name='mistery_evaluado_json'),
    path('marcar-evaluado-mistery/', marcar_evaluado_mistery, name='marcar_evaluado_mistery'),
    path('presupuesto-mes/', presupuesto_mes_json, name='presupuesto_mes_json'),
    path('presupuesto-semana/', presupuesto_semana_json, name='presupuesto_semana_json'),
    path('guardar-presupuesto-semana/', guardar_presupuesto_semana, name='guardar_presupuesto_semana'),
    path('configuracion/', configuracion_incentivos, name='configuracion_incentivos'),
    path('desglose/', desglose_bonos, name='desglose_bonos'),
    path('parsear-prenomina/', parsear_prenomina, name='parsear_prenomina'),
    path('guardar-prenomina/', guardar_prenomina, name='guardar_prenomina'),
]
