# Generated by Django 5.0.14 on 2025-12-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('Modulo_usuarios', 'Acceso al Módulo de Usuarios')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
