# Generated by Django 5.0.14 on 2026-07-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermoduleaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('Modulo_usuarios', 'Acceso al Módulo de Usuarios'), ('auditoria_terminos', 'Acceso a Auditoría de Términos')]},
        ),
    ]
