# Generated by Django 5.0.14 on 2025-09-19 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='auto_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='branch_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='rating_max',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='qtype',
            field=models.CharField(choices=[('text', 'Texto'), ('integer', 'Número entero'), ('decimal', 'Número decimal'), ('single', 'Opciones (selección única)'), ('multiple', 'Opciones (selección múltiple)'), ('rating', 'Calificación'), ('none', 'Sin respuesta')], default='single', max_length=20),
        ),
        migrations.CreateModel(
            name='SurveyAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('all', 'Todos'), ('segmented', 'Segmentado')], default='all', max_length=12)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='surveys.survey')),
                ('users', models.ManyToManyField(blank=True, related_name='survey_audiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('branch_to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='surveys.surveysection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.surveyquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
