# Generated by Django 5.0.14 on 2025-09-25 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_auto_message_survey_is_anonymous_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Enviada'), ('draft', 'Borrador')], default='submitted', max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('survey_title', models.CharField(blank=True, default='', max_length=255)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(max_length=20)),
                ('q_title', models.TextField()),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value_choice', models.IntegerField(blank=True, null=True)),
                ('value_multi', models.JSONField(blank=True, default=list)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse')),
            ],
            options={
                'indexes': [models.Index(fields=['response'], name='surveys_sur_respons_47a805_idx'), models.Index(fields=['question'], name='surveys_sur_questio_61b37a_idx'), models.Index(fields=['q_type'], name='surveys_sur_q_type_afe21e_idx')],
                'unique_together': {('response', 'question')},
            },
        ),
    ]
