# Generated by Django 5.0.14 on 2025-09-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveyresponse_surveyanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='qtype',
            field=models.CharField(choices=[('text', 'Texto'), ('integer', 'Número entero'), ('decimal', 'Número decimal'), ('single', 'Opciones (selección única)'), ('multiple', 'Opciones (selección múltiple)'), ('rating', 'Calificación'), ('assessment', 'Evaluación'), ('frecuency', 'Frecuencia'), ('none', 'Sin respuesta')], default='single', max_length=20),
        ),
    ]
