# Generated by Django 5.0.14 on 2025-12-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_surveyquestion_qtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': [('Modulo_encuestas', 'Acceso al Módulo de Encuestas')]},
        ),
    ]
