# Generated by Django 5.0.14 on 2026-06-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_add_image_qtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='title',
            field=models.CharField(default='Pregunta', max_length=1000),
        ),
    ]
