# Generated by Django 5.0.14 on 2025-10-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_userdailyuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionevent',
            name='event',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('logout_idle', 'Logout por inactividad')], max_length=12),
        ),
    ]
