# Generated by Django 5.0.14 on 2025-12-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_sessionevent_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'permissions': [('Modulo_monitoreo', 'Acceso al Módulo de Monitoreo')]},
        ),
    ]
