# Generated by Django 5.0.14 on 2026-08-25 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_sessionevent_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['module', 'date'], name='monitoring__module_ad7e96_idx'), models.Index(fields=['user', 'date'], name='monitoring__user_id_d5694f_idx')],
                'unique_together': {('user', 'module', 'date')},
            },
        ),
    ]
