# Generated by Django 5.0.14 on 2025-12-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectivecycle',
            options={'permissions': [('Modulo_objetivos', 'Acceso al Módulo de Objetivos')]},
        ),
    ]
