# Generated by Django 5.0.11 on 2025-02-19 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrolledcourse'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('all_users', 'Todo el personal'), ('by_department', 'Por departamento'), ('specific_users', 'Usuarios específicos')], default='all_users', help_text='Tipo de asignación del curso.', max_length=20, verbose_name='Tipo de asignación')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de asignación.', verbose_name='Fecha de asignación')),
                ('assigned_by', models.ForeignKey(help_text='Usuario que asignó el curso.', on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('course', models.ForeignKey(help_text='Curso que se está asignando.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.courseheader', verbose_name='Curso')),
                ('departments', models.ManyToManyField(blank=True, help_text='Departamentos a los que se asigna el curso.', to='departments.department', verbose_name='Departamentos')),
                ('users', models.ManyToManyField(blank=True, help_text='Usuarios específicos a los que se asigna el curso.', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'Asignación de Curso',
                'verbose_name_plural': 'Asignaciones de Cursos',
                'db_table': 'course_assignment',
            },
        ),
        migrations.CreateModel(
            name='CourseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('mandatory', 'Obligatorio'), ('optional', 'Opcional')], default='mandatory', help_text='Define si el curso es obligatorio u opcional.', max_length=10, verbose_name='Tipo de curso')),
                ('sequential', models.BooleanField(default=True, help_text='Indica si el curso debe completarse en orden secuencial.', verbose_name='Secuencialidad')),
                ('deadline', models.IntegerField(default=90, help_text='Plazo límite en días para completar el curso.', verbose_name='Plazo límite')),
                ('audience', models.CharField(choices=[('all_users', 'Todos los usuarios'), ('segment', 'Requiere segmentación')], default='all_users', help_text='Define si el curso está dirigido a todos los usuarios o requiere segmentación.', max_length=15, verbose_name='Audiencia')),
                ('certification', models.BooleanField(default=False, help_text='Indica si el usuario recibe un certificado al completar el curso.', verbose_name='Certificado de finalización')),
                ('requires_signature', models.BooleanField(default=False, help_text='Indica si el usuario debe firmar al completar el curso.', verbose_name='Requiere firma')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización.', null=True, verbose_name='Fecha de actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la configuración.', verbose_name='Fecha de creación')),
                ('course', models.OneToOneField(help_text='Curso al que pertenece esta configuración.', on_delete=django.db.models.deletion.CASCADE, related_name='config', to='courses.courseheader', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Configuración del Curso',
                'verbose_name_plural': 'Configuraciones de Cursos',
                'db_table': 'course_config',
            },
        ),
    ]
