# Generated by Django 5.0.14 on 2025-05-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseassignment_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enlace de video opcional (por ejemplo, YouTube).', null=True, verbose_name='URL del video'),
        ),
    ]
