# Generated by Django 5.0.14 on 2025-06-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explicación de la respuesta (opcional).', null=True, verbose_name='Explicación'),
        ),
    ]
