# Generated by Django 5.0.14 on 2025-06-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_birth_date_employee_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rehire_eligible',
            field=models.BooleanField(default=False, help_text='Indica si puede ser recontratado', verbose_name='Elegible para recontratar'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_reason',
            field=models.CharField(blank=True, help_text='Razón de la baja del empleado', max_length=255, null=True, verbose_name='Motivo de baja'),
        ),
    ]
