# Generated by Django 5.0.14 on 2025-08-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_rehire_eligible_employee_termination_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.CharField(blank=True, help_text='Equipo al que pertenece el empleado', max_length=100, null=True, verbose_name='Equipo'),
        ),
    ]
