# Generated by Django 5.0.14 on 2025-08-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vacation_balance',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Saldo de días de vacaciones disponibles del empleado', max_digits=8, verbose_name='Saldo de vacaciones'),
        ),
    ]
