# Generated by Django 5.0.14 on 2025-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='seniority_raw',
            field=models.CharField(blank=True, help_text='Fecha de antigüedad', max_length=50, null=True, verbose_name='Antigüedad'),
        ),
    ]
