# Generated by Django 5.0.14 on 2025-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_seniority_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salario diario integrado o normal', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='indemnification',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de indemnización', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='responsible',
            field=models.CharField(blank=True, help_text='Nombre del responsable / jefe inmediato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='saving_fund',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fondo de ahorro', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='seniority_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prima de antigüedad', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='separation_gratuity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gratificación por separación', max_digits=12, null=True),
        ),
    ]
