# Generated by Django 5.0.14 on 2026-01-29 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employee', '0008_employee_daily_salary_employee_indemnification_and_more'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(help_text='Número único de identificación del empleado', max_length=20, verbose_name='Número de empleado'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('employee_number', 'start_date'), name='unique_employee_number_start_date'),
        ),
    ]
