# Generated by Django 5.0.14 on 2026-02-03 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employee', '0009_alter_employee_employee_number_and_more'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_employee_number_start_date',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('employee_number', 'start_date', 'curp'), name='unique_employee_identity'),
        ),
    ]
