# Generated by Django 5.0.14 on 2026-02-04 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employee', '0010_remove_employee_unique_employee_number_start_date_and_more'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_employee_identity',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('employee_number', 'start_date', 'curp', 'company'), name='unique_employee_identity'),
        ),
    ]
