# Generated by Django 5.0.14 on 2026-03-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_employee_unique_employee_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='is_evaluable',
            field=models.BooleanField(default=False, help_text='Indica si el puesto participa en las evaluaciones de desempeño', verbose_name='Apto para evaluación'),
        ),
    ]
