# Generated by Django 5.0.14 on 2026-04-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_add_is_evaluable_to_jobposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leader',
            field=models.CharField(blank=True, help_text='Nombre del líder', max_length=255, null=True),
        ),
    ]
