# Generated by Django 5.0.14 on 2026-09-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_add_leader_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leader_fk',
            field=models.ForeignKey(blank=True, help_text='Referencia directa al empleado que es líder de este colaborador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='employee.employee', verbose_name='Líder (FK)'),
        ),
    ]
