# Generated by Django 5.0.11 on 2025-03-24 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo de la ubicación o sucursal', max_length=150, verbose_name='Nombre')),
                ('rfc', models.CharField(help_text='Registro Federal de Contribuyentes de la ubicación', max_length=13, verbose_name='RFC')),
                ('denomination', models.CharField(help_text='Denominación o razón social de la ubicación', max_length=100, verbose_name='Denominación')),
                ('address', models.TextField(help_text='Dirección completa de la ubicación', verbose_name='Domicilio')),
                ('city', models.CharField(help_text='Ciudad donde se encuentra la ubicación', max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, help_text='Estado o provincia donde se encuentra la ubicación', max_length=100, null=True, verbose_name='Estado')),
                ('country', models.CharField(default='México', help_text='País donde se encuentra la ubicación', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, help_text='Código postal de la ubicación', max_length=10, null=True, verbose_name='Código postal')),
                ('email', models.EmailField(help_text='Correo electrónico principal de contacto de la ubicación', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, help_text='Número telefónico principal de la ubicación', max_length=20, null=True, verbose_name='Teléfono')),
                ('station', models.CharField(help_text='Código o identificador de la estación', max_length=50, verbose_name='Estación')),
                ('server', models.CharField(help_text='Nombre o dirección IP del servidor asignado a esta ubicación', max_length=100, verbose_name='Servidor')),
                ('structure', models.CharField(blank=True, help_text='Estructura organizacional de la ubicación', max_length=100, null=True, verbose_name='Estructura')),
                ('group', models.CharField(blank=True, help_text='Grupo al que pertenece esta ubicación', max_length=100, null=True, verbose_name='Grupo')),
                ('tax', models.DecimalField(decimal_places=2, help_text='Porcentaje de IVA aplicable a esta ubicación', max_digits=5, verbose_name='IVA')),
                ('is_headquarters', models.BooleanField(default=False, help_text='Indica si esta ubicación es la casa matriz de la empresa', verbose_name='Casa matriz')),
                ('cost_center', models.CharField(blank=True, help_text='Código del centro de costos asociado a esta ubicación', max_length=20, null=True, verbose_name='Centro de costos')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la ubicación está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó esta ubicación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(help_text='Usuario que actualizó esta ubicación por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['name'],
            },
        ),
    ]
