# Generated by Django 5.0.14 on 2026-07-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_foranea',
            field=models.BooleanField(default=False, help_text='Indica si la estación es foránea (fuera de la ciudad principal)', verbose_name='Foránea'),
        ),
        migrations.AddField(
            model_name='location',
            name='team_key',
            field=models.CharField(blank=True, help_text='Clave que corresponde a Employee.team para identificar empleados de esta estación', max_length=50, null=True, verbose_name='Clave de equipo'),
        ),
    ]
