# Generated by Django 5.0.14 on 2025-07-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='tipo_solicitud',
            field=models.CharField(choices=[('Descanso médico', 'Descanso médico'), ('Días de estudio', 'Días de estudio'), ('Licencia por maternidad', 'Licencia por maternidad'), ('Vacaciones', 'Vacaciones')], default='Vacaciones', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
