# Generated by Django 5.0.14 on 2025-07-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_vacationrequest_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='vacaciones/'),
        ),
    ]
