# Generated by Django 5.0.14 on 2025-07-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0003_alter_vacationrequest_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'permissions': [('can_request_vacation', 'Puede solicitar vacaciones'), ('can_approve_vacation', 'Puede aprobar o rechazar solicitudes'), ('can_view_all_requests', 'Puede ver todas las solicitudes')]},
        ),
    ]
