# Generated by Django 5.0.14 on 2025-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0004_alter_vacationrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Responsable'), ('authorized', 'Pendiente de RH'), ('approved', 'Aprobada / Finalizada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
    ]
