# Generated by Django 5.0.14 on 2025-12-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0006_vacationrequest_manager_approver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'permissions': [('Modulo_vacaciones', 'Acceso al Módulo de Vacaciones'), ('can_request_vacation', 'Puede solicitar vacaciones'), ('can_approve_vacation', 'Puede aprobar o rechazar solicitudes'), ('can_view_all_requests', 'Puede ver todas las solicitudes')]},
        ),
    ]
