# Generated by Django 5.0.14 on 2026-04-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0007_alter_vacationrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='documento_lider',
            field=models.FileField(blank=True, null=True, upload_to='vacaciones/lider/'),
        ),
    ]
