# Generated by Django 5.0.14 on 2026-04-07 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0008_add_documento_lider'),
    ]

    operations = [
    ]
