# Generated by Django 5.0.14 on 2026-04-07 23:00

from django.db import migrations, models


def migrate_comments(apps, schema_editor):
    VacationRequest = apps.get_model('vacations', 'VacationRequest')
    TAG_LIDER = '[Responsable]:'
    TAG_RH = '[RH]:'
    for req in VacationRequest.objects.all():
        text = req.reason or ''
        idx_lider = text.find(TAG_LIDER)
        idx_rh = text.find(TAG_RH)

        if idx_lider == -1 and idx_rh == -1:
            pass
        elif idx_lider != -1 and idx_rh == -1:
            req.comentario_lider = text[idx_lider + len(TAG_LIDER):].strip()
            req.reason = text[:idx_lider].strip()
            req.save()
        elif idx_lider == -1 and idx_rh != -1:
            req.comentario_rh = text[idx_rh + len(TAG_RH):].strip()
            req.reason = text[:idx_rh].strip()
            req.save()
        else:
            req.comentario_lider = text[idx_lider + len(TAG_LIDER):idx_rh].strip()
            req.comentario_rh = text[idx_rh + len(TAG_RH):].strip()
            req.reason = text[:idx_lider].strip()
            req.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0009_add_comentario_lider_rh'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='comentario_lider',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='comentario_rh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_comments, migrations.RunPython.noop),
    ]
