# Generated by Django 5.0.14 on 2026-05-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0012_vacationrequest_zona_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Responsable'), ('zona_pending', 'Pendiente de Jefe de Zona'), ('authorized', 'Pendiente de RH'), ('approved', 'Aprobada / Finalizada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
    ]
