# Generated by Django 5.0.14 on 2026-09-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0013_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Responsable'), ('zona_pending', 'Pendiente de Jefe de Zona'), ('authorized', 'Pendiente de RH'), ('approved', 'Aprobada / Finalizada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada por RH')], default='pending', max_length=20),
        ),
    ]
