# Generated by Django 5.0.14 on 2026-09-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0014_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='tipo_solicitud',
            field=models.CharField(choices=[('Descanso médico', 'Descanso médico'), ('Días de estudio', 'Días de estudio'), ('Home Office', 'Home Office'), ('Licencia por maternidad', 'Licencia por maternidad'), ('Vacaciones', 'Vacaciones')], default='Vacaciones', max_length=50),
        ),
    ]
