# Generated by Django 5.0.14 on 2026-09-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0016_alter_vacationrequest_tipo_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaInhabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Día Inhábil',
                'verbose_name_plural': 'Días Inhábiles',
                'ordering': ['fecha'],
            },
        ),
    ]
