# Generated by Django 5.0.14 on 2025-12-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('Modulo_organigrama', 'Acceso al Módulo de Organigrama')]},
        ),
    ]
