# Generated by Django 5.0.14 on 2025-12-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='module',
            field=models.CharField(blank=True, choices=[('usuarios', 'Usuarios'), ('noticias', 'Noticias'), ('comunicados', 'Comunicados'), ('constancias', 'Solicitud de constancias'), ('encuestas', 'Encuestas'), ('cursos', 'Cursos'), ('organigrama', 'Organigrama'), ('vacaciones', 'Vacaciones y permisos'), ('evaluacion', 'Evaluación de desempeño'), ('objetivos', 'Objetivos'), ('archivo', 'Archivo'), ('onboarding', 'Onboarding'), ('mis_documentos', 'Mis documentos'), ('vacantes', 'Vacantes'), ('politicas', 'Políticas internas'), ('plan_carrera', 'Plan de carrera'), ('requisiciones', 'Requisición de personal')], max_length=40),
        ),
    ]
